apiVersion: choreo.dev/v1alpha1
kind: Component
metadata:
  name: todo-backend
  description: Backend service for MERN Todo Application
spec:
  type: service
  runtime: nodejs18
  build:
    context: .
    dockerfile: Dockerfile
  endpoints:
    - name: api
      port: 8080
      path: /api
      protocol: http
  environment:
    - name: PORT
      value: "8080"
    - name: NODE_ENV
      value: "production"
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  healthCheck:
    path: /api/health
    port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
