apiVersion: choreo.dev/v1alpha1
kind: Component
metadata:
  name: todo-backend
spec:
  type: service
  runtime: nodejs18
  build:
    context: .
    dockerfile: Dockerfile
  endpoints:
    - name: api
      port: 8080
      type: REST
      networkVisibility: Public
      context: /
