# Choreo Backend Service Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
data:
  PORT: "8080"
  NODE_ENV: "production"
  # MongoDB URI will be set via environment variables in Choreo
  # CORS_ORIGIN will be set to the frontend URL after deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: choreo/todo-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: todo-backend-secrets
              key: mongodb-uri
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: todo-backend-config
              key: cors-origin
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
spec:
  selector:
    app: todo-backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
