apiVersion: choreo.dev/v1alpha1
kind: Component
metadata:
  name: todo-backend
  description: "Backend service for MERN Todo Application - Choreo Deployment"
spec:
  type: service
  build:
    type: dockerfile
    context: .
    dockerfile: Dockerfile
    buildpack: false
  endpoints:
    - name: api
      port: 8080
      type: REST
      networkVisibility: Public
      context: /
      healthCheck:
        path: /api/health
        port: 8080
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
  runtime:
    env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "8080"
      - name: CORS_ORIGIN
        value: "*"
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
  observability:
    metrics:
      enabled: true
    tracing:
      enabled: true
    logging:
      level: info
