apiVersion: choreo.dev/v1alpha1
kind: Component
metadata:
  name: todo-backend
spec:
  type: service
  build:
    type: dockerfile
    context: .
    dockerfile: Dockerfile
    buildpack: false
  endpoints:
    - name: api
      port: 8080
      type: REST
      networkVisibility: Public
      context: /
