# Monitoring and Logging Configuration for Choreo Deployment

apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
data:
  # Log level configuration
  LOG_LEVEL: "info"
  # Enable structured logging
  STRUCTURED_LOGGING: "true"
  # Application name for log identification
  APP_NAME: "todo-app"
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: todo-backend-monitor
  labels:
    app: todo-backend
spec:
  selector:
    matchLabels:
      app: todo-backend
  endpoints:
  - port: 8080
    path: /api/metrics
    interval: 30s
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: todo-frontend-monitor
  labels:
    app: todo-frontend
spec:
  selector:
    matchLabels:
      app: todo-frontend
  endpoints:
  - port: 3000
    path: /metrics
    interval: 30s
---
# PrometheusRule for alerting
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: todo-app-alerts
spec:
  groups:
  - name: todo-app
    rules:
    - alert: TodoBackendDown
      expr: up{job="todo-backend"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Todo Backend is down"
        description: "Todo Backend has been down for more than 1 minute."
    - alert: TodoFrontendDown
      expr: up{job="todo-frontend"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Todo Frontend is down"
        description: "Todo Frontend has been down for more than 1 minute."
    - alert: HighMemoryUsage
      expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage detected"
        description: "Container {{ $labels.container }} is using more than 80% of its memory limit."
