openapi: 3.0.3
info:
  title: Todo API
  description: RESTful API for managing todos in a MERN stack application
  version: 1.0.0
servers:
  - url: https://todo-backend.choreo.dev
    description: Production server
  - url: http://localhost:8080
    description: Development server
paths:
  /api/health:
    get:
      summary: Health check
      description: Check if the service is running
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Server is running"
                  timestamp:
                    type: string
                    format: date-time
  /api/todos:
    get:
      summary: Get all todos
      responses:
        '200':
          description: Successful response
    post:
      summary: Create a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoRequest'
      responses:
        '201':
          description: Todo created
  /api/todos/{id}:
    get:
      summary: Get a specific todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
    put:
      summary: Update a todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoRequest'
      responses:
        '200':
          description: Todo updated
    delete:
      summary: Delete a todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Todo deleted
  /api/todos/{id}/toggle:
    patch:
      summary: Toggle todo completion status
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Status toggled
components:
  schemas:
    Todo:
      type: object
      properties:
        _id:
          type: string
        text:
          type: string
        completed:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CreateTodoRequest:
      type: object
      properties:
        text:
          type: string
        completed:
          type: boolean
          default: false
      required:
        - text
    UpdateTodoRequest:
      type: object
      properties:
        text:
          type: string
        completed:
          type: boolean
